// This file is generated by generate_file_names.rs
// Do not edit manually.

use obfstr::obfstr as s;
use wasm_bindgen::intern as i;

///Retrieves hashed file name index
///
///If the pkg_name is not trackable from caller (for instance when using `.unwrap_js`)
///and the caller file is a lib.rs uses the first lib.rs from partial file paths.
///
///When this happens find the error with only the line number.
pub fn find_file_index(pkg_name: Option<&str>, file: &str) -> Option<u16> {
    //Partial file paths:
    // 0   => background\build.rs
    // 1   => background\src\dispatcher.rs
    // 2   => background\src\exports.rs
    // 3   => background\src\imports.rs
    // 4   => background\src\lib.rs
    // 5   => background\src\task.rs
    // 6   => common\src\error\mod.rs
    // 7   => common\src\file_names.rs
    // 8   => common\src\js_imports\mod.rs
    // 9   => common\src\lib.rs
    // 10  => common\src\log\mod.rs
    // 11  => common\src\macros\mod.rs
    // 12  => common\src\web_extension_sys\action.rs
    // 13  => common\src\web_extension_sys\cookies.rs
    // 14  => common\src\web_extension_sys\debugger.rs
    // 15  => common\src\web_extension_sys\mod.rs
    // 16  => common\src\web_extension_sys\runtime\mod.rs
    // 17  => common\src\web_extension_sys\runtime\port.rs
    // 18  => common\src\web_extension_sys\scripting.rs
    // 19  => common\src\web_extension_sys\storage\mod.rs
    // 20  => common\src\web_extension_sys\tabs.rs
    // 21  => common\src\web_extension_sys\windows.rs
    // 22  => foreground\build.rs
    // 23  => foreground\src\addons\accept_group\html.rs
    // 24  => foreground\src\addons\accept_group\mod.rs
    // 25  => foreground\src\addons\accept_summon\html.rs
    // 26  => foreground\src\addons\accept_summon\mod.rs
    // 27  => foreground\src\addons\adaptive_builds\html.rs
    // 28  => foreground\src\addons\adaptive_builds\mod.rs
    // 29  => foreground\src\addons\anty_duch\html.rs
    // 30  => foreground\src\addons\anty_duch\mod.rs
    // 31  => foreground\src\addons\better_group_invites\html.rs
    // 32  => foreground\src\addons\better_group_invites\mod.rs
    // 33  => foreground\src\addons\better_messages\html.rs
    // 34  => foreground\src\addons\better_messages\mod.rs
    // 35  => foreground\src\addons\better_who_is_here\html.rs
    // 36  => foreground\src\addons\better_who_is_here\mod.rs
    // 37  => foreground\src\addons\kastrat\html.rs
    // 38  => foreground\src\addons\kastrat\mod.rs
    // 39  => foreground\src\addons\mod.rs
    // 40  => foreground\src\addons\online_peers\html.rs
    // 41  => foreground\src\addons\online_peers\mod.rs
    // 42  => foreground\src\addons\smart_forge\html.rs
    // 43  => foreground\src\addons\smart_forge\mod.rs
    // 44  => foreground\src\addons\znacznik\descriptors.rs
    // 45  => foreground\src\addons\znacznik\html.rs
    // 46  => foreground\src\addons\znacznik\mod.rs
    // 47  => foreground\src\addon_window\decors.rs
    // 48  => foreground\src\addon_window\mod.rs
    // 49  => foreground\src\addon_window\ui_components.rs
    // 50  => foreground\src\color_mark.rs
    // 51  => foreground\src\dispatcher.rs
    // 52  => foreground\src\globals\addons.rs
    // 53  => foreground\src\globals\emitter.rs
    // 54  => foreground\src\globals\hero.rs
    // 55  => foreground\src\globals\hero_settings.rs
    // 56  => foreground\src\globals\items.rs
    // 57  => foreground\src\globals\mod.rs
    // 58  => foreground\src\globals\npcs.rs
    // 59  => foreground\src\globals\others.rs
    // 60  => foreground\src\globals\party.rs
    // 61  => foreground\src\globals\peers.rs
    // 62  => foreground\src\globals\players_online.rs
    // 63  => foreground\src\globals\port\mod.rs
    // 64  => foreground\src\globals\port\task.rs
    // 65  => foreground\src\globals\town.rs
    // 66  => foreground\src\globals\user.rs
    // 67  => foreground\src\globals\world_config.rs
    // 68  => foreground\src\imports\engine\communication.rs
    // 69  => foreground\src\imports\engine\mod.rs
    // 70  => foreground\src\imports\engine\other.rs
    // 71  => foreground\src\imports\engine\party.rs
    // 72  => foreground\src\imports\engine\peer.rs
    // 73  => foreground\src\imports\mod.rs
    // 74  => foreground\src\interface\addons.rs
    // 75  => foreground\src\interface\dom_utils.rs
    // 76  => foreground\src\interface\mod.rs
    // 77  => foreground\src\interface\tips_parser.rs
    // 78  => foreground\src\interface\window.rs
    // 79  => foreground\src\lib.rs
    // 80  => foreground\src\macros\mod.rs
    // 81  => foreground\src\utils\dominator_helpers.rs
    // 82  => foreground\src\utils\logging.rs
    // 83  => foreground\src\utils\mod.rs
    // 84  => foreground\src\utils\window_events.rs
    // 85  => popup\src\exports.rs
    // 86  => popup\src\lib.rs
    // 87  => popup\src\task.rs
    [
        i(s!("background\\build.rs")),
        i(s!("background\\src\\dispatcher.rs")),
        i(s!("background\\src\\exports.rs")),
        i(s!("background\\src\\imports.rs")),
        i(s!("background\\src\\lib.rs")),
        i(s!("background\\src\\task.rs")),
        i(s!("common\\src\\error\\mod.rs")),
        i(s!("common\\src\\file_names.rs")),
        i(s!("common\\src\\js_imports\\mod.rs")),
        i(s!("common\\src\\lib.rs")),
        i(s!("common\\src\\log\\mod.rs")),
        i(s!("common\\src\\macros\\mod.rs")),
        i(s!("common\\src\\web_extension_sys\\action.rs")),
        i(s!("common\\src\\web_extension_sys\\cookies.rs")),
        i(s!("common\\src\\web_extension_sys\\debugger.rs")),
        i(s!("common\\src\\web_extension_sys\\mod.rs")),
        i(s!("common\\src\\web_extension_sys\\runtime\\mod.rs")),
        i(s!("common\\src\\web_extension_sys\\runtime\\port.rs")),
        i(s!("common\\src\\web_extension_sys\\scripting.rs")),
        i(s!("common\\src\\web_extension_sys\\storage\\mod.rs")),
        i(s!("common\\src\\web_extension_sys\\tabs.rs")),
        i(s!("common\\src\\web_extension_sys\\windows.rs")),
        i(s!("foreground\\build.rs")),
        i(s!("foreground\\src\\addons\\accept_group\\html.rs")),
        i(s!("foreground\\src\\addons\\accept_group\\mod.rs")),
        i(s!("foreground\\src\\addons\\accept_summon\\html.rs")),
        i(s!("foreground\\src\\addons\\accept_summon\\mod.rs")),
        i(s!("foreground\\src\\addons\\adaptive_builds\\html.rs")),
        i(s!("foreground\\src\\addons\\adaptive_builds\\mod.rs")),
        i(s!("foreground\\src\\addons\\anty_duch\\html.rs")),
        i(s!("foreground\\src\\addons\\anty_duch\\mod.rs")),
        i(s!("foreground\\src\\addons\\better_group_invites\\html.rs")),
        i(s!("foreground\\src\\addons\\better_group_invites\\mod.rs")),
        i(s!("foreground\\src\\addons\\better_messages\\html.rs")),
        i(s!("foreground\\src\\addons\\better_messages\\mod.rs")),
        i(s!("foreground\\src\\addons\\better_who_is_here\\html.rs")),
        i(s!("foreground\\src\\addons\\better_who_is_here\\mod.rs")),
        i(s!("foreground\\src\\addons\\kastrat\\html.rs")),
        i(s!("foreground\\src\\addons\\kastrat\\mod.rs")),
        i(s!("foreground\\src\\addons\\mod.rs")),
        i(s!("foreground\\src\\addons\\online_peers\\html.rs")),
        i(s!("foreground\\src\\addons\\online_peers\\mod.rs")),
        i(s!("foreground\\src\\addons\\smart_forge\\html.rs")),
        i(s!("foreground\\src\\addons\\smart_forge\\mod.rs")),
        i(s!("foreground\\src\\addons\\znacznik\\descriptors.rs")),
        i(s!("foreground\\src\\addons\\znacznik\\html.rs")),
        i(s!("foreground\\src\\addons\\znacznik\\mod.rs")),
        i(s!("foreground\\src\\addon_window\\decors.rs")),
        i(s!("foreground\\src\\addon_window\\mod.rs")),
        i(s!("foreground\\src\\addon_window\\ui_components.rs")),
        i(s!("foreground\\src\\color_mark.rs")),
        i(s!("foreground\\src\\dispatcher.rs")),
        i(s!("foreground\\src\\globals\\addons.rs")),
        i(s!("foreground\\src\\globals\\emitter.rs")),
        i(s!("foreground\\src\\globals\\hero.rs")),
        i(s!("foreground\\src\\globals\\hero_settings.rs")),
        i(s!("foreground\\src\\globals\\items.rs")),
        i(s!("foreground\\src\\globals\\mod.rs")),
        i(s!("foreground\\src\\globals\\npcs.rs")),
        i(s!("foreground\\src\\globals\\others.rs")),
        i(s!("foreground\\src\\globals\\party.rs")),
        i(s!("foreground\\src\\globals\\peers.rs")),
        i(s!("foreground\\src\\globals\\players_online.rs")),
        i(s!("foreground\\src\\globals\\port\\mod.rs")),
        i(s!("foreground\\src\\globals\\port\\task.rs")),
        i(s!("foreground\\src\\globals\\town.rs")),
        i(s!("foreground\\src\\globals\\user.rs")),
        i(s!("foreground\\src\\globals\\world_config.rs")),
        i(s!("foreground\\src\\imports\\engine\\communication.rs")),
        i(s!("foreground\\src\\imports\\engine\\mod.rs")),
        i(s!("foreground\\src\\imports\\engine\\other.rs")),
        i(s!("foreground\\src\\imports\\engine\\party.rs")),
        i(s!("foreground\\src\\imports\\engine\\peer.rs")),
        i(s!("foreground\\src\\imports\\mod.rs")),
        i(s!("foreground\\src\\interface\\addons.rs")),
        i(s!("foreground\\src\\interface\\dom_utils.rs")),
        i(s!("foreground\\src\\interface\\mod.rs")),
        i(s!("foreground\\src\\interface\\tips_parser.rs")),
        i(s!("foreground\\src\\interface\\window.rs")),
        i(s!("foreground\\src\\lib.rs")),
        i(s!("foreground\\src\\macros\\mod.rs")),
        i(s!("foreground\\src\\utils\\dominator_helpers.rs")),
        i(s!("foreground\\src\\utils\\logging.rs")),
        i(s!("foreground\\src\\utils\\mod.rs")),
        i(s!("foreground\\src\\utils\\window_events.rs")),
        i(s!("popup\\src\\exports.rs")),
        i(s!("popup\\src\\lib.rs")),
        i(s!("popup\\src\\task.rs")),
    ]
    .iter()
    .enumerate()
    .find(|(_, partial_file_path)| {
        file.ends_with(*partial_file_path)
            && match pkg_name {
                Some(pkg_name) => partial_file_path.contains(pkg_name),
                None => true,
            }
    })
    .map(|(index, _)| index as u16)
}
