use std::collections::{BTreeMap, HashMap};

use futures_signals::signal_map::MutableBTreeMap;

use super::{Descriptor, Id, LocationAlias};

//pub const NPC_PATH: &str = "https://micc.garmory-cdn.cloud/obrazki/npc/";

macro_rules! descriptions {
    ($($map_id:expr => { $txt:expr, $img:expr }),+ $(,)?) => {
        [
            $(($map_id, Descriptor::new($txt.to_owned(), concat!("https://micc.garmory-cdn.cloud/obrazki/npc/", $img).to_owned()))),+
        ]
    };
}

pub(super) fn get_default() -> MutableBTreeMap<Id, Descriptor> {
    let descriptors = descriptions!(
        // TITANS:
        189  /*Mroczna Pieczara p.0*/ => { "ORLA", "tyt/dziewicza_orlica.gif" },
        1746 /*Grota Caerbannoga*/ => { "KIC", "tyt/killerrabbit.gif" },
        6949 /*Bandyckie Chowisko*/ => { "RENE", "tyt/renegat_baulus.gif" },
        7060 /*Wulkan Politraki - przedsionek*/ => { "ARCY", "tyt/archdemon.gif" },
        7477 /*Lokum Złych Goblinów p.4*/ => {"ZOONS", "tyt/versus-zoons.gif"},
        6477 /*Jaskinia Ulotnych Wspomnień*/ => { "ŁOWKA", "tyt/lowcz-wspo-driady.gif" },
        6476 /*Więzienie Demonów*/ => { "PRZYZ", "tyt/przyz_demon_sekta.gif" },
        2024 /*Grota Jaszczurzych Koszmarów p.2*/ => { "MAGUA", "tyt/maddok-tytan.gif" },
        5709 /*Teotihuacan - przedsionek*/ => { "TEZA", "tyt/tezcatlipoca.gif" },
        3312 /*Sekretne Przejście Kapłanów*/ => { "BARB", "tyt/hebrehoth_smokoludzie.gif" },
        2355 /*Przejście Władców Mrozu*/ => { "TH", "tyt/ice_king.gif" },
        // COLOSSUS:
        3361 /*Pradawne Wzgórze Przodków*/ => { "36", "kol/mamlambo_final2.gif" },
        3883 /*Pieczara Szaleńców - przedsionek*/ => { "63", "kol/bazyliszek.gif" },
        202  /*Pieczara Szaleńców - sala 4*/ => { "63", "kol/bazyliszek.gif" },
        4046 /*Zmarzlina Amaimona Soplorękiego - przedsionek*/ => { "83", "kol/soploreki.gif" },
        1387 /*Skały Mroźnych Śpiewów*/ => { "83", "kol/soploreki.gif" },
        7353 /*Głębia Przeklętych Fal - przedsionek*/ => { "114", "kol/kolos-wodnik.gif" },
        1739 /*Archipelag Bremus An*/ => { "114", "kol/kolos-wodnik.gif" },
        4161 /*Przepaść Zadumy - przedsionek*/ => { "144", "kol/kolos-wazka.gif" },
        349  /*Jezioro Ważek*/ => { "144", "kol/kolos-wazka.gif" },
        4066 /*Czeluść Chimerycznej Natury - przedsionek*/ => { "167", "kol/hydrokora.gif" },
        3535 /*Przełęcz Krwistego Posłańca*/ => { "167", "kol/hydrokora.gif" },
        4196 /*Grobowiec Przeklętego Krakania - przedsionek*/ => { "198", "kol/kolkrucz.gif" },
        6052 /*Krypty Bezsennych p.2 s.2*/ => { "198", "kol/kolkrucz.gif" },
        4206 /*Grota Przebiegłego Tkacza - przedsionek*/ => { "225", "kol/kolos-pajak.gif" },
        1131 /*Pajęczy Las*/ => { "225", "kol/kolos-pajak.gif" },
        4266 /*Grota Martwodrzewów - przedsionek*/ => { "252", "kol/kolos-dendro.gif" },
        3596 /*Regiel Zabłąkanych*/ => { "252", "kol/kolos-dendro.gif" },
        4268 /*Katakumby Antycznego Gniewu - przedsionek*/ => { "279", "kol/kolos-drakolisz.gif" },
        3037 /*Katakumby Krwawych Wypraw*/ => { "279", "kol/kolos-drakolisz.gif" },
        // EII 1-100:
        1060 /*Kryjówka Dzikich Kotów*/ => { "MUSH", "e2/st-puma.gif" },
        632  /*Las Tropicieli*/ => { "KOTO", "e1/kotolak_lowca.gif" },
        5738 /*Przeklęta Strażnica - podziemia p.2 s.1*/ => { "SHAE", "e2/demonszef.gif" },
        5740 /*Przeklęta Strażnica - podziemia p.2 s.3*/ => { "SHAE", "e2/demonszef.gif" },
        2532 /*Schowek na Łupy*/ => { "ZORG", "e2/zbir-e2-zorg.gif" },
        727  /*Podmokła Dolina*/ => { "WłAD", "e2/gobmag2.gif" },
        4156 /*Pieczara Kwiku - sala 1*/ => { "TYRT", "e2/dzik.gif" },
        5293 /*Skalne Turnie*/ => { "TOL", "e2/tollok_shimger.gif" },
        2308 /*Stary Kupiecki Trakt*/ => { "ALIAS", "e2/zbir-szczet.gif" },
        177  /*Mokra Grota p.2*/ => { "AGAR", "e2/glut_agar.gif" },
        125  /*Stare Wyrobisko p.3*/ => { "RAZIU", "e2/razuglag.gif" },
        2729 /*Lazurytowa Grota p.4*/ => { "KOB", "e2/kobold07.gif" },
        5395 /*Kopalnia Kapiącego Miodu p.2 - sala Owadziej Matki*/ => { "MATKA", "e2/zadlak-e2-owadzia-matka.gif" },
        333  /*Wioska Gnolli*/ => { "VARI", "e2/gnoll11.gif" },
        3437 /*Jaskinia Gnollich Szamanów - komnata Kozuga*/ => { "KOZUG", "e2/gnoll12.gif" },
        6537 /*Kamienna Jaskinia - sala 3*/ => { "JOTUN", "e2/kam_olbrzym-b.gif" },
        6632 /*Głębokie Skałki p.3*/ => { "TOLE", "e2/tollok_jask_utumatu.gif" },
        6625 /*Krypty Dusz Śniegu p.2*/ => { "LISZ", "e2/lisz_demilisze.gif" },
        6623 /*Erem Czarnego Słońca p.5*/ => { "GRAB", "e2/nieu_mnich_grabarz.gif" },
        1204 /*Firnowa Grota p.2*/ => { "STOPA", "e2/wlochacze_wielka_stopa.gif" },
        6615 /*Świątynia Andarum - zbrojownia*/ => { "ZBROJ", "e2/magaz_zbrojmistrz.gif" },
        6634 /*Wylęgarnia Choukkerów p.1*/ => { "CHOUK", "e2/dlawiciel5.gif" },
        6772 /*Kopalnia Margorii*/ => { "NADZ", "e2/nadzorczyni_krasnoludow.gif" },
        6773 /*Margoria*/ => { "MORTH", "e2/krasnolud_boss.gif" },
        1324 /*Zapomniany Święty Gaj p.2*/ => { "WIDMO", "e2/lesne_widmo.gif" },
        3466 /*Grota Samotnych Dusz p.6*/ => { "OHYD", "e2/ugrape2.gif" },
        1150 /*Kamienna Strażnica - Sala Chwały*/ => { "GOPA", "e2/goplana.gif" },
        6781 /*Zagrzybiałe Ścieżki p.3*/ => { "GNOM", "e2/gnom_figlid.gif" },
        3765 /*Dolina Centaurów*/ => { "ZYF", "e2/cent-zyfryd.gif" },
        //EII 101-150
        229  /*Las Dziwów*/ => { "KAMB", "e2/kambion.gif" },
        6938 /*Podziemia Zniszczonej Wieży p.5*/ => { "JERT", "e2/moloch-jertek.gif" },
        6944 /*Zabłocona Jama p.2 - Sala Błotnistych Odmętów*/ => { "M.RYC", "e2/blotniaki_milosnik_rycerzy.gif" },
        6946 /*Zabłocona Jama p.2 - Sala Magicznego Błota*/ => { "M.MAG", "e2/blotniaki_milosnik_magii.gif" },
        6945 /*Zabłocona Jama p.2 - Sala Duszącej Stęchlizny*/ => { "M.ŁOW", "e2/blotniaki_milosnik_lowcow.gif" },
        7066 /*Skalne Cmentarzysko p.4*/ => { "Ł.C.", "e2/alghul-czaszka-1a.gif" },
        7069 /*Piramida Pustynnego Władcy p.3*/ => { "OZIRUS", "e2/mumia-ozirus.gif" },
        7357 /*Jama Morskiej Macki p.1 - sala 3*/ => { "MORSKI", "e2/osmiornica-1b.gif" },
        7369 /*Opuszczony statek - pokład pod rufą*/ => { "KRAB", "e2/krab_big3.gif" },
        1741 /*Wyspa Rem*/ => { "KRAB", "e2/krab_big3.gif" },
        7368 /*Twierdza Rogogłowych - Sala Byka*/ => { "BYK", "e2/ingotia_minotaur-7a.gif" },
        7375 /*Piaskowa Pułapka - Grota Piaskowej Śmierci*/ => { "STWOR", "e2/stworzyciel.gif" },
        7057 /*Wulkan Politraki p.1 - sala 3*/ => { "IFRYT", "e2/magradit_ifryt.gif" },
        3409 /*Ukryta Grota Morskich Diabłów - magazyn*/ => { "JACK", "e2/pirat-2b.gif" },
        1527 /*Ukryta Grota Morskich Diabłów - siedziba*/ => { "HELGA", "e2/pirat01.gif" },
        1526 /*Ukryta Grota Morskich Diabłów - skarbiec*/ => { "HENRY", "e1/pirat5b.gif" },
        7352 /*Piaszczysta Grota p.1 - sala 2*/ => { "EOL", "e2/piaskowy_potwor-6a.gif" },
        6955 /*Kopalnia Żółtego Kruszcu p.2 - sala 1*/ => { "GRUB", "e2/grubber-ochlaj.gif" },
        7466 /*Kuźnia Worundriela - Komnata Żaru*/ => { "WOREK", "e2/worundriel02.gif" },
        7339 /*Chata wójta Fistuły*/ => { "WOJT", "e2/goral-e2-wojt-fistula.gif" },
        351  /*Babi Wzgórek*/ => { "TESC", "e2/goral-e2-tesciowa-rumcajsa.gif" },
        7454 /*Cenotaf Berserkerów p.1 - sala 2*/ => {"AMUNO", "e2/amuno.gif"},
        //EII 151-200
        7441 /*Mała Twierdza - sala główna*/ => {"FODUG", "e2/fodug_zolash.gif"},
        7474 /*Lokum Złych Goblinów - warsztat*/ => {"GOONS", "e2/goons_asterus-1a.gif"},
        1322 /*Laboratorium Adariel*/ => {"ADA", "e2/tri_adariel.gif"},
        5856 /*Grota Orczej Hordy p.2 s.3*/ => { "BUREK", "e2/orkczd.gif" },
        5851 /*Grota Orczych Szamanów p.3 s.1*/ => {"SHEBA", "e2/r_orc_sheba.gif"},
        5872 /*Nawiedzone Kazamaty p.4*/ => {"DWK", "e2/duch_wladcy_kl.gif"},
        5861 /*Sala Rady Orków*/ => { "SK", "e2/praork_low_elita.gif" },
        5862 /*Sala Królewska*/ => { "GRUBA", "e2/prakrolowa.gif" },
        7345 /*Kryształowa Grota - Sala Smutku*/ => { "SNIEG", "e2/krolowa-sniegu.gif" },
        6054 /*Drzewo Dusz p.1*/ => { "CHRYZ", "e2/chryzoprenia.gif" },
        6057 /*Grota Arbor s.2*/ => { "CERAS", "e2/drzewoe2.gif" },
        1912 /*Zalana Grota*/ => { "FURB", "e2/forbol03.gif" },
        6053 /*Krypty Bezsennych p.3*/ => { "TORKA", "e2/thuz-patr1.gif" },
        2063 /*Przysiółek Valmirów*/ => { "BREH", "e2/draki-breheret-1b.gif" },
        972  /*Szlamowe Kanały*/ => { "MYSZ", "e2/krolszczur.gif" },
        5940 /*Przerażające Sypialnie*/ => { "SADA", "e2/sekta-sadolia.gif" },
        //EII 201-300
        5941 /*Tajemnicza Siedziba*/ => { "TS", "e2/sekta-gothardus.gif" },
        5942 /*Sala Spowiedzi Konających*/ => { "SAT", "e2/sekta-sataniel.gif" },
        5945 /*Sale Rozdzierania*/ => { "BERGA", "e2/sekta-bergermona.gif" },
        5943 /*Sala Tysiąca Świec*/ => { "ZUF", "e2/sekta-zufulus.gif" },
        2766 /*Ołtarz Pajęczej Bogini*/ => { "MARLL", "e2/marlloth.gif" },
        1481 /*Grota Błotnej Magii*/ => { "M.MAD", "e2/maddok5.gif" },
        1142 /*Arachnitopia p.5*/ => { "P5", "e2/regina-e2.gif" },
        1462 /*Jaszczurze Korytarze p.4 - sala 3*/ => { "PANC", "e2/maddok_roz.gif" },
        3627 /*Krzaczasta Grota - korytarz*/ => { "SILVA", "e2/silvanasus.gif" },
        3597 /*Źródło Zakorzenionego Ludu*/ => { "DENDR", "e2/dendroculus.gif" },
        3610 /*Jaskinia Korzennego Czaru p.1 - sala 1*/ => { "DENDR", "e2/dendroculus.gif" },
        5657 /*Złota Góra p.2 s.1*/ => { "TOLY", "e2/bolita.gif" },
        1901 /*Niecka Xiuh Atl*/ => { "CIUT", "e2/maho-cuaitl.gif" },
        4056 /*Potępione Zamczysko - sala ofiarna*/ => { "SYBA", "e2/tri2_witch_e2.gif" },
        5694 /*Zachodni Mictlan p.8*/ => { "JAJO", "e2/mahoplowca.gif" },
        5684 /*Wschodni Mictlan p.8*/ => { "P9", "e2/quetzalcoatl.gif" },
        3035 /*Katakumby Gwałtownej Śmierci*/ => { "CHOP", "e2/chopesh2.gif" },
        3039 /*Grobowiec Seta*/ => { "SET", "e2/szkiel_set.gif" },
        3327 /*Urwisko Vapora*/ => { "TER", "e2/terrorzaur_pus.gif" },
        3335 /*Jaskinia Smoczej Paszczy p.2*/ => { "TER", "e2/terrorzaur_pus.gif" },
        3340 /*Świątynia Hebrehotha - sala ofiary*/ => { "VERA", "e2/bar_smoczyca.gif" },
        3341 /*Świątynia Hebrehotha - sala czciciela*/ => { "CHAE", "e2/bar_smokoszef.gif" },
        3339 /*Świątynia Hebrehotha - przedsionek*/ => { "PUST", "e2/bar_smokoszef.gif" },
        6064 /*Drzewo Życia p.2*/ => { "NYMF", "e2/nymphemonia.gif" },
        2353 /*Sala Lodowej Magii*/ => { "ART", "e2/wl-mrozu03.gif" },
        2356 /*Sala Mroźnych Strzał*/ => { "FUR", "e2/wl-mrozu02.gif" },
        2354 /*Sala Mroźnych Szeptów*/ => { "ZOR", "e2/wl-mrozu01.gif" },
    );

    MutableBTreeMap::with_values(BTreeMap::from(descriptors))
}

macro_rules! alias_list {
    ($($map_id:expr => $map_name:expr),+ $(,)?) => {
        [
            $(($map_id, LocationAlias($map_name.to_owned()))),+
        ]
    };
}

pub(super) fn alias_list() -> HashMap<Id, LocationAlias> {
    let list = alias_list! [
        // TITANS:
        189  => "Mroczna Pieczara p.0",
        1746 => "Grota Caerbannoga",
        6949 => "Bandyckie Chowisko",
        7060 => "Wulkan Politraki - przedsionek",
        7477 => "Lokum Złych Goblinów p.4",
        6477 => "Jaskinia Ulotnych Wspomnień",
        6476 => "Więzienie Demonów",
        2024 => "Grota Jaszczurzych Koszmarów p.2",
        5709 => "Teotihuacan - przedsionek",
        3312 => "Sekretne Przejście Kapłanów",
        2355 => "Przejście Władców Mrozu",
        // COLOSSUS:
        3361 => "Pradawne Wzgórze Przodków",
        3883 => "Pieczara Szaleńców - przedsionek",
        202  => "Pieczara Szaleńców - sala 4",
        4046 => "Zmarzlina Amaimona Soplorękiego - przedsionek",
        1387 => "Skały Mroźnych Śpiewów",
        7353 => "Głębia Przeklętych Fal - przedsionek",
        1739 => "Archipelag Bremus An",
        4161 => "Przepaść Zadumy - przedsionek",
        349  => "Jezioro Ważek",
        4066 => "Czeluść Chimerycznej Natury - przedsionek",
        3535 => "Przełęcz Krwistego Posłańca",
        4196 => "Grobowiec Przeklętego Krakania - przedsionek",
        6052 => "Krypty Bezsennych p.2 s.2",
        4206 => "Grota Przebiegłego Tkacza - przedsionek",
        1131 => "Pajęczy Las",
        4266 => "Grota Martwodrzewów - przedsionek",
        3596 => "Regiel Zabłąkanych",
        4268 => "Katakumby Antycznego Gniewu - przedsionek",
        3037 => "Katakumby Krwawych Wypraw",
        // EII 1-100:
        1060 => "Kryjówka Dzikich Kotów",
        632  => "Las Tropicieli",
        5738 => "Przeklęta Strażnica - podziemia p.2 s.1",
        5740 => "Przeklęta Strażnica - podziemia p.2 s.3",
        2532 => "Schowek na Łupy",
        727  => "Podmokła Dolina",
        4156 => "Pieczara Kwiku - sala 1",
        5293 => "Skalne Turnie",
        2308 => "Stary Kupiecki Trakt",
        177  => "Mokra Grota p.2",
        125  => "Stare Wyrobisko p.3",
        2729 => "Lazurytowa Grota p.4",
        5395 => "Kopalnia Kapiącego Miodu p.2 - sala Owadziej Matki",
        333  => "Wioska Gnolli",
        3437 => "Jaskinia Gnollich Szamanów - komnata Kozuga",
        6537 => "Kamienna Jaskinia - sala 3",
        6632 => "Głębokie Skałki p.3",
        6625 => "Krypty Dusz Śniegu p.2",
        6623 => "Erem Czarnego Słońca p.5",
        1204 => "Firnowa Grota p.2",
        6615 => "Świątynia Andarum - zbrojownia",
        6634 => "Wylęgarnia Choukkerów p.1",
        6772 => "Kopalnia Margorii",
        6773 => "Margoria",
        1324 => "Zapomniany Święty Gaj p.2",
        3466 => "Grota Samotnych Dusz p.6",
        1150 => "Kamienna Strażnica - Sala Chwały",
        6781 => "Zagrzybiałe Ścieżki p.3",
        3765 => "Dolina Centaurów",
        // EII 101-150
        229  => "Las Dziwów",
        6938 => "Podziemia Zniszczonej Wieży p.5",
        6944 => "Zabłocona Jama p.2 - Sala Błotnistych Odmętów",
        6946 => "Zabłocona Jama p.2 - Sala Magicznego Błota",
        6945 => "Zabłocona Jama p.2 - Sala Duszącej Stęchlizny",
        7066 => "Skalne Cmentarzysko p.4",
        7069 => "Piramida Pustynnego Władcy p.3",
        7357 => "Jama Morskiej Macki p.1 - sala 3",
        7369 => "Opuszczony statek - pokład pod rufą",
        1741 => "Wyspa Rem",
        7368 => "Twierdza Rogogłowych - Sala Byka",
        7375 => "Piaskowa Pułapka - Grota Piaskowej Śmierci",
        7057 => "Wulkan Politraki p.1 - sala 3",
        3409 => "Ukryta Grota Morskich Diabłów - magazyn",
        1527 => "Ukryta Grota Morskich Diabłów - siedziba",
        1526 => "Ukryta Grota Morskich Diabłów - skarbiec",
        7352 => "Piaszczysta Grota p.1 - sala 2",
        6955 => "Kopalnia Żółtego Kruszcu p.2 - sala 1",
        7466 => "Kuźnia Worundriela - Komnata Żaru",
        7339 => "Chata wójta Fistuły",
        351  => "Babi Wzgórek",
        7454 => "Cenotaf Berserkerów p.1 - sala 2",
        // EII 151-200
        7441 => "Mała Twierdza - sala główna",
        7474 => "Lokum Złych Goblinów - warsztat",
        1322 => "Laboratorium Adariel",
        5856 => "Grota Orczej Hordy p.2 s.3",
        5851 => "Grota Orczych Szamanów p.3 s.1",
        5872 => "Nawiedzone Kazamaty p.4",
        5861 => "Sala Rady Orków",
        5862 => "Sala Królewska",
        7345 => "Kryształowa Grota - Sala Smutku",
        6054 => "Drzewo Dusz p.1",
        6057 => "Grota Arbor s.2",
        1912 => "Zalana Grota",
        6053 => "Krypty Bezsennych p.3",
        2063 => "Przysiółek Valmirów",
        972  => "Szlamowe Kanały",
        5940 => "Przerażające Sypialnie",
        // EII 201-300
        5941 => "Tajemnicza Siedziba",
        5942 => "Sala Spowiedzi Konających",
        5945 => "Sale Rozdzierania",
        5943 => "Sala Tysiąca Świec",
        2766 => "Ołtarz Pajęczej Bogini",
        1481 => "Grota Błotnej Magii",
        1142 => "Arachnitopia p.5",
        1462 => "Jaszczurze Korytarze p.4 - sala 3",
        3627 => "Krzaczasta Grota - korytarz",
        3597 => "Źródło Zakorzenionego Ludu",
        3610 => "Jaskinia Korzennego Czaru p.1 - sala 1",
        5657 => "Złota Góra p.2 s.1",
        1901 => "Niecka Xiuh Atl",
        4056 => "Potępione Zamczysko - sala ofiarna",
        5694 => "Zachodni Mictlan p.8",
        5684 => "Wschodni Mictlan p.8",
        3035 => "Katakumby Gwałtownej Śmierci",
        3039 => "Grobowiec Seta",
        3327 => "Urwisko Vapora",
        3335 => "Jaskinia Smoczej Paszczy p.2",
        3340 => "Świątynia Hebrehotha - sala ofiary",
        3341 => "Świątynia Hebrehotha - sala czciciela",
        3339 => "Świątynia Hebrehotha - przedsionek",
        6064 => "Drzewo Życia p.2",
        2353 => "Sala Lodowej Magii",
        2356 => "Sala Mroźnych Strzał",
        2354 => "Sala Mroźnych Szeptów",
    ];
    HashMap::from(list)
}
